apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-image-deployment
  labels:
    app: sample-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-image
  template:
    metadata:
      labels:
        app: sample-image
    spec:
      containers:
      - name: sample-image-cont
        image: abinaya.azurecr.io/sampleapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-image-service
spec:
  selector:
    app: sample-image
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
