apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-image-deployment
  labels:
    app: sample-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-image
  template:
    metadata:
      labels:
        app: sample-image
    spec:
      containers:
      - name: sample-image-container
        image: abinaya.azurecr.io/sample:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 49160
---
apiVersion: v1
kind: Service
metadata:
  name: sample-image-service
spec:
  selector:
    app: sample-image
  ports:
    - protocol: TCP
      port: 49160
      targetPort: 49160
  type: LoadBalancer
